-- Curated public directory, verified 2026-09-13.
-- IMPORTANT: verification means identity/basic public information was checked.
-- It does NOT imply endorsement or a guaranteed health-anxiety-friendly experience.

DELETE FROM professional_specialties WHERE professional_id IN (SELECT id FROM professionals WHERE is_demo = 1);
DELETE FROM facility_study_types WHERE facility_id IN (SELECT id FROM facilities WHERE is_demo = 1);
DELETE FROM professionals WHERE is_demo = 1;
DELETE FROM facilities WHERE is_demo = 1;

INSERT OR IGNORE INTO specialties (id,name,slug,category,active) VALUES
('spec-psicologia','Psicologia','psicologia','mental_health',1),
('spec-psiquiatria','Psiquiatria','psiquiatria','mental_health',1),
('spec-cardiologia','Cardiologia','cardiologia','medical',1),
('spec-clinica','Clinica medica','clinica-medica','medical',1),
('spec-gastro','Gastroenterologia','gastroenterologia','medical',1),
('spec-dermatologia','Dermatologia','dermatologia','medical',1),
('spec-neurologia','Neurologia','neurologia','medical',1),
('spec-otorrino','Otorrinolaringologia','otorrinolaringologia','medical',1),
('spec-endocrino','Endocrinologia','endocrinologia','medical',1),
('spec-gineco','Ginecologia','ginecologia','medical',1),
('spec-urologia','Urologia','urologia','medical',1),
('spec-oftalmo','Oftalmologia','oftalmologia','medical',1);

INSERT OR IGNORE INTO locations (id,country_code,province,city,zone,neighborhood) VALUES
('loc-palermo-curated','AR','CABA','CABA','Norte','Palermo'),
('loc-recoleta-curated','AR','CABA','CABA','Norte','Recoleta'),
('loc-belgrano-curated','AR','CABA','CABA','Norte','Belgrano'),
('loc-nunez-curated','AR','CABA','CABA','Norte','Nunez'),
('loc-quilmes-curated','AR','Buenos Aires','Quilmes','Sur','Quilmes Centro'),
('loc-caba-curated','AR','CABA','CABA',NULL,NULL);

INSERT OR IGNORE INTO professionals
(id,slug,first_name,last_name,display_name,bio,primary_specialty_id,license_number,institution,location_id,address_public,website_url,public_phone,care_modes,verification_status,source_notes,created_at,updated_at,is_demo)
VALUES
('pro-ricardo-perez-rivera','dr-ricardo-perez-rivera','Ricardo','Perez Rivera','Dr. Ricardo Perez Rivera','Psiquiatra y director de TOC Argentina, centro dedicado al TOC y trastornos relacionados, incluida la hipocondria/ansiedad por la salud.','spec-psiquiatria',NULL,'TOC Argentina','loc-palermo-curated','Bulnes 1937, 1 B, CABA','https://www.tocargentina.com.ar/DrPerezRivera.html','+54 9 11 6405-9055','["in_person"]','verified','Fuente: TOC Argentina. El centro declara tratamiento de TOC, trastornos relacionados e hipocondria mediante abordaje cognitivo-conductual y farmacologico cuando corresponde. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-camila-steigmeier','lic-camila-steigmeier','Camila','Steigmeier','Lic. Camila Steigmeier','Psicologa especializada en TOC, certificada BTTI por la International OCD Foundation.','spec-psicologia','MN 54309','TOC Argentina','loc-palermo-curated','Palermo, CABA','https://www.tocargentina.com.ar/equipo.html','+54 9 11 6405-9055','["in_person"]','verified','Fuente: equipo TOC Argentina. Especialista en TOC, certificacion BTTI IOCDF y formacion TCC especifica. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-agnese-parisi','lic-agnese-parisi','Agnese','Parisi','Lic. Agnese Parisi','Psicologa con especializacion en psicologia clinica/TCC, trastornos de ansiedad y formacion especifica en TOC.','spec-psicologia','MN 69344','TOC Argentina','loc-palermo-curated','Palermo, CABA','https://www.tocargentina.com.ar/equipo.html','+54 9 11 6405-9055','["in_person"]','verified','Fuente: equipo TOC Argentina. Declara formacion en TOC y tratamiento cognitivo-conductual del TOC. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-florencia-portero','lic-florencia-portero','Maria Florencia','Portero','Lic. Maria Florencia Portero','Psicologa especialista en psicoterapia cognitivo-conductual integrativa y diplomada en TOC y espectro.','spec-psicologia','MN 53389','TOC Argentina','loc-palermo-curated','Palermo, CABA','https://www.tocargentina.com.ar/equipo.html','+54 9 11 6405-9055','["in_person"]','verified','Fuente: equipo TOC Argentina. Diplomada en TOC y Espectro por TOC Argentina. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-carola-wainhaus','dra-carola-wainhaus','Carola','Wainhaus','Dra. Carola Wainhaus','Medica psiquiatra del equipo de TOC Argentina, con posgrado en trastornos de ansiedad y psicofarmacologia.','spec-psiquiatria','MN 172033','TOC Argentina','loc-palermo-curated','Palermo, CABA','https://www.tocargentina.com.ar/equipo.html','+54 9 11 6405-9055','["in_person"]','verified','Fuente: equipo TOC Argentina. Medica psiquiatra y admisora en TOC Argentina; posgrado en trastornos de ansiedad. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-leonel-galeppi','lic-leonel-galeppi','Leonel','Galeppi','Lic. Leonel Galeppi','Psicologo con entrenamiento clinico en TOC por International OCD Foundation.','spec-psicologia','MN 60173 / MP 62403','TOC Argentina','loc-quilmes-curated','Quilmes Centro, Buenos Aires','https://www.tocargentina.com.ar/equipo.html','+54 9 11 6405-9055','["in_person"]','verified','Fuente: equipo TOC Argentina. Entrenamiento clinico en TOC por IOCDF y formacion en trastornos de ansiedad. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-romina-raffo','lic-romina-raffo','Romina','Raffo','Lic. Romina Raffo','Psicologa clinica con orientacion TCC y formacion/docencia en TOC y espectro obsesivo-compulsivo.','spec-psicologia','MN 37484','TOC Argentina','loc-nunez-curated','Nunez, CABA','https://www.tocargentina.com.ar/equipo.html','+54 9 11 6405-9055','["in_person"]','verified','Fuente: equipo TOC Argentina. Orientacion TCC y actividad docente en TOC y espectro. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-marcos-irrazabal','lic-marcos-irrazabal','Marcos','Irrazabal','Lic. Marcos Irrazabal','Psicologo BTTI entrenado por IOCDF. Ofrece Exposicion y Prevencion de Respuesta (ERP) para pacientes con TOC.','spec-psicologia',NULL,NULL,'loc-recoleta-curated','Av. Gral. Las Heras 2670, CABA','https://iocdf.org/providers/irrazabal-marcos/','+54 11 7655-1184','["virtual"]','verified','Fuente: International OCD Foundation. Perfil declara experiencia amplia en TOC/trastornos relacionados y uso de ERP. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-daniela-gilotti','lic-daniela-belen-gilotti','Daniela Belen','Gilotti','Lic. Daniela Belen Gilotti','Psicologa BTTI entrenada por IOCDF, con parte sustancial de su practica dedicada al TOC y trastornos relacionados mediante TCC con EPR.','spec-psicologia',NULL,NULL,'loc-caba-curated',NULL,'https://iocdf.org/es/proveedores/gilotti-daniela-belen/','+54 11 3044-2054','["in_person","virtual"]','verified','Fuente: International OCD Foundation. El perfil declara 50-60% de practica dedicada a TOC/trastornos relacionados y TCC con EPR. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-noelia-mayen-poclaba','lic-noelia-mayen-poclaba','Noelia','Mayen Poclaba','Lic. Noelia Mayen Poclaba','Psicologa UBA con orientacion TCC/DBT que declara especializacion en TOC y trabajo con EPR.','spec-psicologia',NULL,NULL,'loc-caba-curated','Viamonte 1592, CABA','https://www.psychologytoday.com/ar/psicologos/noelia-mayen-poclaba-buenos-aires-ba/1275763',NULL,'["in_person","virtual"]','verified','Fuente: Psychology Today. Perfil profesional verificado por el directorio; declara trabajo con TOC mediante Exposicion y Prevencion de Respuesta. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-victoria-tomeo','lic-victoria-tomeo','Victoria','Tomeo','Lic. Victoria Tomeo','Psicologa que declara experiencia en trastornos de ansiedad, TOC y fobias, utilizando ERP, ACT y mindfulness.','spec-psicologia',NULL,NULL,'loc-caba-curated',NULL,'https://www.doctoraliar.com/perfil/victoria-tomeo-4',NULL,'["in_person","virtual"]','verified','Fuente: Doctoralia. El perfil declara experiencia en ansiedad, TOC y uso de ERP/ACT. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-ana-paula-rodriguez-villegas','dra-ana-paula-rodriguez-villegas','Ana Paula','Rodriguez Villegas','Dra. Ana Paula Rodriguez Villegas','Psiquiatra listada con experiencia en TOC, ansiedad y ataques de panico.','spec-psiquiatria',NULL,NULL,'loc-belgrano-curated','La Pampa 2477, Piso 11 A, CABA','https://www.topdoctors.com.ar/trastorno-obsesivo-compulsivo/buenos-aires-capital-caba/',NULL,'["in_person"]','verified','Fuente: Top Doctors Argentina. Figura como psiquiatra experta en TOC y ansiedad. No demuestra especificamente manejo de ansiedad por la salud; requiere experiencias de la comunidad. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-vanesa-ordines','dra-vanesa-ordines','Vanesa','Ordines','Dra. Vanesa Ordines','Psiquiatra listada con experiencia en TOC, ataques de panico y ansiedad.','spec-psiquiatria',NULL,NULL,'loc-caba-curated',NULL,'https://www.topdoctors.com.ar/trastorno-obsesivo-compulsivo/buenos-aires-capital-caba/',NULL,'["virtual"]','verified','Fuente: Top Doctors Argentina. Figura como experta en TOC y ansiedad. Requiere experiencias de la comunidad para valorar compatibilidad con ansiedad por la salud. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('pro-alicia-portela','dra-alicia-andrea-portela','Alicia Andrea','Portela','Dra. Alicia Andrea Portela','Psiquiatra listada con experiencia en TOC y psicofarmacologia.','spec-psiquiatria',NULL,NULL,'loc-recoleta-curated','Junin 977, 5 C, CABA','https://www.topdoctors.com.ar/trastorno-obsesivo-compulsivo/buenos-aires-capital-caba/',NULL,'["in_person"]','verified','Fuente: Top Doctors Argentina. Figura como experta en TOC. Requiere experiencias de la comunidad para valorar compatibilidad con ansiedad por la salud. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0);

INSERT OR IGNORE INTO facilities
(id,slug,name,description,facility_type,location_id,address_public,website_url,public_phone,verification_status,source_notes,created_at,updated_at,is_demo)
VALUES
('fac-toc-argentina','toc-argentina','TOC Argentina','Centro psicologico y psiquiatrico dedicado al TOC y trastornos relacionados, incluida la hipocondria/ansiedad por la salud.','clinic','loc-palermo-curated','Bulnes 1937, 1 B, CABA','https://www.tocargentina.com.ar/','+54 9 11 6405-9055','verified','Fuente institucional: TOC Argentina. Declara explicitamente tratamiento de hipocondria/trastornos de sintomas somaticos, TOC y trastornos relacionados con TCC y abordaje psiquiatrico. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0),
('fac-instituto-realize','instituto-realize','Instituto Realize','Instituto de psicologia y psiquiatria con trayectoria en investigacion y tratamientos de TOC y trastornos relacionados.','clinic','loc-caba-curated',NULL,'https://toctaniaborda.com/instituto-realize-2/',NULL,'verified','Fuente institucional: Instituto Realize / Tania Borda. Declara trayectoria en investigacion y tratamientos de psicologia y psiquiatria vinculados al TOC. Verificado 2026-09-13.','2026-09-13T17:30:00.000Z','2026-09-13T17:30:00.000Z',0);
